<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_keyword</name>
   <tag></tag>
   <elementGuidId>d6fd7ab7-12bd-4094-b37d-ec6ae47eec7c</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>keyword</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>js-autocomplete-input js-search-field js-main-search js-ss-type</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search over 150,000 products</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-click-track</name>
      <type>Main</type>
      <value>search_bar_text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-click-location</name>
      <type>Main</type>
      <value>search_bar_text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-qa</name>
      <type>Main</type>
      <value>input-search-field</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;doc3&quot;)/div[@class=&quot;js-scroll-menu-container store-nav-wrap&quot;]/div[@class=&quot;store-nav-header clearfix&quot;]/div[@class=&quot;js-scroll-menu-mid-bar&quot;]/div[@class=&quot;js-autocomplete search-bar&quot;]/form[@class=&quot;js-search-wrap search-wrap  focused  placeholder&quot;]/div[@class=&quot;headertable  js-search-border&quot;]/div[@class=&quot;js-autocomplete-container  bgcolorwhite&quot;]/input[@class=&quot;js-autocomplete-input js-search-field js-main-search js-ss-type&quot;]</value>
   </webElementProperties>
</WebElementEntity>
