<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>firstsearchresult</name>
   <tag></tag>
   <elementGuidId>8e4c77ae-29e0-4872-bea2-cc4b60653177</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'img_ILIF4625' and @alt = 'Marcus Swivel Faux Leather Barstools (Set of 2)' and @src = 'https://img.zcdn.com.au/lf/79/hash/38173/18661842/4/Marcus+Swivel+Faux+Leather+Barstools+%2528Set+of+2%2529.jpg']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@class='sb_prod_details_block js-ss-click js-prod-click'][1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>225</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>225</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>blocklevel</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>img_ILIF4625</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Marcus Swivel Faux Leather Barstools (Set of 2)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://img.zcdn.com.au/lf/79/hash/38173/18661842/4/Marcus+Swivel+Faux+Leather+Barstools+%2528Set+of+2%2529.jpg</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;img_ILIF4625&quot;)</value>
   </webElementProperties>
</WebElementEntity>
